services:
  go:
    build:
      context: .
      dockerfile: Dockerfile.prod
    hostname: go
    container_name: go
    env_file:
      - .env
    volumes:
      - go-mod-cache:/go/pkg/mod
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - app-network
    depends_on:
      - database
