FROM golang:1.25-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o bin/ecoply ./entrypoint


FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache tzdata

COPY --from=build /app/bin/ecoply .
COPY --from=build /app/web /app/web
RUN chmod +x ecoply

CMD [ "./ecoply" ]